services:
  db:
    image: postgres:latest
    container_name: postgres_test
    env_file:
      - ".env.test"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  cache:
    image: redis:latest
    container_name: redis_test
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - ".env.test"
    networks:
      - app_network
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
