services:
  db:
    image: postgres:latest
    container_name: postgres_test
    env_file:
      - ".env.test"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
